### ISSUE TITLE
多线程服务端如何实现向客户端发送消息呢

### ISSUE THREAD

**Issue by Tegrisco** [gongjianbo/HelloQtNetwork#1]

**Comment by gongjianbo** [comment]
客户端连上了不就可以发了

**Comment by Tegrisco** [comment]
感谢作者回复！
本人最近刚入门qt，之前是想做一个Tcp多线程收发的程序，但是这边的MultithreadTcpServer例子里只展示了客户端发服务端的，自己结合了SimpleTcpServer例子之后写的程序会报下面的错，所以才提了这个issue
`QObject::connect: Cannot queue arguments of type 'QTextCursor'`
后面参考下面两篇博客已经解决了
[子线程 Cannot queue arguments of type 'QTextCursor'](https://www.cnblogs.com/daiguoxi/p/14014657.html)
[Qt程序错误...](https://blog.csdn.net/hu626626/article/details/103860351)

归根结底还是自己对线程和信号与槽机制理解不够，但是这个项目写的很详细，给了我很大帮助，再次感谢作者！
